# site settings
title: Karishma
subtitle: Cheyenne
email: asthanakarishma@gmail.com
description: Do you even exist if you're not taking up cyberspace with your content? Developing a website to feel more real (how ironic). Peruse at your leisure!
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
#street_address: 1234 Somewhere Road
city: Los Angeles
state: CA
#zip_code: 55577
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
#facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/karishma-asthana-918378b4/
#pinterest_url:
#slack_url:
twitter: @karishmachey

# build settings
markdown: kramdown

sass:
  style: compressed
